package com.localllm.assistant.history.model;

/**
 * Defines the possible roles for a message within a chat conversation history.
 */
public enum MessageRole {
    /**
     * Message originated from the end-user.
     */
    USER,

    /**
     * Message generated by the AI assistant (LLM).
     */
    ASSISTANT,

    /**
     * System-level message providing context or instructions (less common in simple history).
     */
    SYSTEM,

    /**
     * Message representing retrieved code context (internal representation, might not be stored directly as a 'role').
     */
    CONTEXT
} 